set -sg escape-time 0

set -g history-limit 100000

set -g base-index 1
set -g pane-base-index 1

set -g mouse on

set -g focus-events on

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g set-titles on
set -g set-titles-string "#S / #W"

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind | split-window -h -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}" 
bind c new-window -c "#{pane_current_path}"

setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

PANE_RESIZE=5
bind -r H resize-pane -L $PANE_RESIZE
bind -r J resize-pane -D $PANE_RESIZE
bind -r K resize-pane -U $PANE_RESIZE
bind -r L resize-pane -R $PANE_RESIZE

bind C-g display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"

bind C-n display-popup -E 'bash -i -c "read -p \"Session Name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

bind C-t display-popup -d "#{pane_current_path}" -E "zsh"

set -g status-position top
set -g status-justify absolute-centre

WHITE="#a9b1d6"
BLACK="#15161e"
BLUE="#7aa2f7"
CYAN="#7dcfff"
GREEN="#9ece6a"
PURPLE="#bb9af7"
RED="#f7768e"
YELLOW="#e0af68"
BRIGHT_WHITE="#c0caf5"
BRIGHT_BLACK="#414868"
BRIGHT_BLUE="#7aa2f7"
BRIGHT_CYAN="#7dcfff"
BRIGHT_GREEN="#9ece6a"
BRIGHT_PURPLE="#9d7cd8"
BRIGHT_RED="#f7768e"
BRIGHT_YELLOW="#e0caf5"

FG="#c0caf5"
BG="#1a1b26"
SELECTION_BG="#283457"

TRIANGLE_OPEN="#(printf '\uE0B2')"
TRIANGLE_CLOSE="#(printf '\uE0B0')"
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"

set -g status-bg $BG
set -g status-fg $FG
set -g status-style "bg=${BG} fg=${FG} nobold"
set -g window-status-style "bg=${BG} fg=${FG}"
set -g window-status-bell-style "bg=${SELECTION_BG} fg=${BG} nobold"
set -g window-status-activity-style "bg=${WHITE} fg=${BG}"
set -g message-style "bg=${YELLOW} fg=${BG} fill=${YELLOW}"
set -g message-command-style "bg=${YELLOW} fg=${BG} fill=${YELLOW}"

set -g pane-border-style "fg=${FG}"
set -g pane-active-border-style "fg=${SELECTION_BG}"

window_status_format=" #I:#W "
window_status_current_format="${HALF_ROUND_OPEN}#[bg=${FG} fg=${BG}]#I:#W#[bg=${BG} fg=${FG}]${HALF_ROUND_CLOSE}"
session_status_format="#[bg=${BLUE} fg=${BG}] #S #[bg=${BG} fg=${BLUE}]${TRIANGLE_CLOSE}"

status_left="#{?client_prefix,,${session_status_format}}"
set -g status-left "$status_left"

status_right="#[bg=${BG} fg=${BLUE}]${TRIANGLE_OPEN}#[bg=${BLUE} fg=${BG}]#{=21:pane_title}"
set -g status-right "$status_right"

set -g window-status-format "${window_status_format}"
set -g window-status-current-format "${window_status_current_format}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
